[package]
name = "legos"
version = "0.1.0"
authors = ["Yashasvi Sriram Patkuri <yash.3997@gmail.com>"]
edition = "2018"

[dev-dependencies]
legos_curve_fitting = { path = "legos_curve_fitting", version = "0.1.0" }
legos_utils = { path = "legos_utils", version = "0.1.0" }
plotters = "0.2.15"

