[package]
name = "legos"
version = "0.1.0"
authors = ["Yashasvi Sriram Patkuri <yash.3997@gmail.com>"]
edition = "2018"

[dev-dependencies]
legos_test_tools = { path = "legos_test_tools" }
gnuplot = "0.0.37"
